# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - main

#-------------------------------------------------#
pr:
  - main

#-------------------------------------------------#
pool:
  vmImage: 'windows-latest'

#-------------------------------------------------#
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  buildNumber: '$(date:yyyyMMdd)$(rev:.r)'

#-------------------------------------------------#
steps:
- task: DotNetCoreCLI@2
  name: BuildProjects
  displayName: 'Build Projects'
 
  inputs:
    command: build
    projects: '**/*.sln'
    arguments: '--configuration $(buildConfiguration)'
#--------------------------------------------------#
- task: DotNetCoreCLI@2
  name: 'Publish'
  displayName: 'Publish Artifacts'
  inputs:
    command: publish
    projects: '**/*.sln'
    zipAfterPublish: true
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
#-------------------------------------------------#
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  condition: succeededOrFailed()
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: drop
  

#-------------------------------------------------#