
variables:
- name: BuildParameters.RestoreBuildProjects
  value: 'src/SPT.eCommerce.Api.Initial/SPT.eCommerce.Api.Initial.sln'
- name: BuildParameters.reportDirectory
  value: ''
- name: BuildParameters.codeCoverageTool
  value: JaCoCo
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - "src/SPT.eCommerce.Api.Initial/*"
pr:
  branches:
    include:
    - main 
  paths:
    include:
      - "src/SPT.eCommerce.Api.Initial/*"
      
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self

#-------------------------------------------------#
steps:

- task: DotNetCoreCLI@2
  name: BuildProjects
  displayName: 'Build Projects'
 
  inputs:
    command: build
    projects: 'src/SPT.eCommerce.Api.Initial/SPT.eCommerce.Initial.sln'
    arguments: '--configuration $(buildConfiguration)'
#--------------------------------------------------#
- task: DotNetCoreCLI@2
  name: 'Publish'
  displayName: 'Publish Artifacts'
  inputs:
    command: publish
    projects: 'src/SPT.eCommerce.Api.Initial/SPT.eCommerce.Initial.sln.sln'
    zipAfterPublish: true
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
#-------------------------------------------------#
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  condition: succeededOrFailed()
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: drop
  

#-------------------------------------------------#