variables:
  solution: '**/SPT.eCommerce.Cart.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  buildNumber: '$(date:yyyyMMdd)$(rev:.r)'
  codeCoverageTool: 'JaCoCo'

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - "src/SPT.eCommerce.Cart/*"
pr:
  branches:
    include:
    - main 
  paths:
    include:
      - "src/SPT.eCommerce.Cart/*"
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self

#-------------------------------------------------#
steps:
- checkout: self
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: $(solution)

- task: DotNetCoreCLI@2
  name: BuildProjects
  displayName: 'Build Projects'
 
  inputs:
    command: build
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'
#--------------------------------------------------#
- task: DotNetCoreCLI@2
  name: 'Publish'
  displayName: 'Publish'
  inputs:
    command: publish
    projects: '**/SPT.eCommerce.Cart.sln'
    zipAfterPublish: true
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)'
#-------------------------------------------------#
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifact'
  condition: succeeded()
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: CartApp
  

#-------------------------------------------------#